config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :posts
  resources :users, only: [:index, :show]
  resources :comments
  resources :likes
  resources :friendships

  post 'friendships/:id', to: 'friendships#update'

  root to: "home#index"
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :authenticate_user!, only: %i[index new]
  def index
    @posts = Post.all
    @comments = Comment.all
    @post = Post.new
    @comment = Comment.new
    @like = Like.new
  end

  def new; end

  def edit; end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/_posts.html.erb
<div class="feed-posts">
    <% @posts.each do |post| %>

    <% if Friendship.accepted_friendships(current_user, post.user).exists? or post.user == current_user %>

    <div class="post-field">
        <%= post.content %> <br>
        <%= "By: " +  post.user.name %> <br>

        <% post.comments.each do |comment| %>


        <%= comment.text %> <br>
        <%="By:" + comment.user.name %> <br>



        <% end %>

        <%= form_for(@comment, url: comments_url, method: 'post') do |f| %>
        <%= f.text_area :text , class: "ftext"%> <br>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.hidden_field :post_id, :value => post.id %>
        <%= f.submit "Comment" ,class: "button-comment" %>
        <% end %>

        <%= form_for(@like, url: likes_url, method: 'post') do |ff| %>
        <%= ff.hidden_field :user_id, :value => current_user.id %>
        <%= ff.hidden_field :post_id, :value => post.id %>
        <%= ff.submit post.likes.count ,class: "button-comment" %>
        <% end %>

    </div>
    <% end %>

    <% end %>
</div>

app/views/home/_sendpost.html.erb
<div class="feed-send">

    <%= form_for(@post, url: posts_url, method: 'post') do |f| %>

    <div class="field">
        <%= f.label :title, "Title" ,class: "form-letter"%> <br>
        <%= f.text_field :title , class: "ftext"%> <br>
    </div>

    <div class="field">
        <%= f.label :content, "Content" ,class: "form-letter" %> <br>
        <%= f.text_area :content , class: "ftext"%> <br>
    </div>

    <div class="field">
        <%= f.submit "Send" ,class: "form-letter" %>
    </div>
    <% end %>
</div>

app/views/home/index.html.erb
<div class="container  justify-content-center">

    <%= render "home/sendpost" %>




        <%= render "home/posts" %>



</div>
</div>